# Omakase Ruby styling for Rails
inherit_gem:
  rubocop-rails-omakase: rubocop.yml

plugins:
  - rubocop-performance
  - rubocop-rails
  - rubocop-minitest

# Overwrite or add rules to create your own house style
#
# # Use `[a, [b, c]]`