# Omakase Ruby styling for Rails
inherit_gem: { rubocop-rails-omakase: rubocop.yml }

# Overwrite or add rules to create your own house style
#
# # Use `[a, [b, c]]` not `[ a, [ b, c ] ]`
# Layout/SpaceInsideArrayLiteralBrackets:
#   Enabled: false

# Use `[ a, b, c ]` with spaces inside brackets
Layout/SpaceInsideArrayLiteralBrackets:
  EnforcedStyle: space
